### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by emilnordh** [gaearon/flowcheck-loader#1]
I can't get it to work with webpack sourcemaps.

**Comment by gaearon** [comment]
Sorry, I no longer intend to support this project, so I am closing.

**Comment by gaearon** [comment]
Reopening, as the future maintainer might want to look into this.

**Comment by gcanti** [comment]
This repo is deprecated, please migrate to [babel-plugin-tcomb](https://github.com/gcanti/babel-plugin-tcomb) which is now Flow compatible
